### ISSUE TITLE
Support for swapping embeds

### ISSUE THREAD

**Issue by jwmcglynn** [hkgnp/logseq-swapblocks-plugin#2]
I would like to swap an embed block with its source, however this doesn't appear possible since a message pops up that says "Please do a swap only for reference blocks".

Is this possible to support, or is there another feature that already does this?

**Comment by benjypng** [comment]
Hi! Thanks for using so many of the plugins!

Hmm do you have a screenshot example of an embed block?

**Comment by jwmcglynn** [comment]
Hopefully this demo video will help:

https://user-images.githubusercontent.com/103489/151953100-4e30a80a-344d-4d06-ba79-4057afc22af8.mp4

For embeds, they have the syntax of `{{embed ((block-ref))}}`, and show child blocks as well.  I use the "Dev" theme, which puts a big border around them, but normally embeds aren't as prominent.

It would be great if this also could detect `{{embed ((block-ref))}}`.

**Comment by benjypng** [comment]
Ah, I must admit that I didn't even know that embed block references exist.

Added support for it in v1.2 in the marketplace.

**Comment by jwmcglynn** [comment]
Just tried it out, thank you so much!

**Comment by benjypng** [comment]
Welcome!
