### ISSUE TITLE
Unexpected unindentation.

### ISSUE THREAD

**Issue by WsinGithub** [hkgnp/logseq-swapblocks-plugin#3]
![TODO2](https://user-images.githubusercontent.com/55137994/153762655-8855466e-eff1-4b98-accf-f566232eb979.gif)

Amazing plugin! THX a lot :D

**Comment by WsinGithub** [comment]
It occurs when the bolck is the first one of its (unoder list) level.

**Comment by benjypng** [comment]
Hi, sorry about it. I am not really sure what the issue is. Can't really tell from your video.

**Comment by WsinGithub** [comment]
> Hi, sorry about it. I am not really sure what the issue is. Can't really tell from your video.

The original block "333" should be at level-3 in the outline, which is a child-block of '222'.
After swaping, the ref become level-2, which is brother-block of '222.

**Comment by WsinGithub** [comment]
The point is that the indentation changes, which I don't want...

**Comment by benjypng** [comment]
Ah I see. The problem with gifs is that you can never know when the gif starts and when it ends.

Will look into this.

**Comment by chs33** [comment]
Upvote this, encounter the same problem.  It makes more sense for the level of indentation to be the same before and after swap for both origin and swapped one, i.e. the indentation structure is preserved. It is not the case currently:

before swap 
![image](https://user-images.githubusercontent.com/16418270/160293566-329433db-8c07-4187-a9d6-41b75ad5ee7e.png)

after swap - _the indentation structure is not preserved_
![image](https://user-images.githubusercontent.com/16418270/160293618-28363d95-1280-4b6e-9151-2cbd5953e972.png)

**Comment by benjypng** [comment]
Hi all, 
Please update to v1.2.2 and see if the issue still persists?

**Comment by WsinGithub** [comment]
> Hi all, Please update to v1.2.2 and see if the issue still persists?

It works! THX <3
