### ISSUE TITLE
"Apply children as block references " has bugs

### ISSUE THREAD

**Issue by jimmy909090** [hkgnp/logseq-swapblocks-plugin#8]
Before re-index, everything looks well. After re-index, those block references as children are invalidated:

![temp247](https://user-images.githubusercontent.com/113656415/191204930-d490a3fc-b4f0-45ad-b9d1-3b6b780f4c83.gif)

**Comment by axelav** [comment]
This same bug occurs if you sync your graph between multiple machines. The "Apply children as block references" references are valid on the original machine, but invalid on any synced machine.

**Comment by benjypng** [comment]
> Before re-index, everything looks well. After re-index, those block references as children are invalidated:
> 
> ![temp247](https://user-images.githubusercontent.com/113656415/191204930-d490a3fc-b4f0-45ad-b9d1-3b6b780f4c83.gif) [ ![temp247](https://user-images.githubusercontent.com/113656415/191204930-d490a3fc-b4f0-45ad-b9d1-3b6b780f4c83.gif) ](https://user-images.githubusercontent.com/113656415/191204930-d490a3fc-b4f0-45ad-b9d1-3b6b780f4c83.gif) [ ](https://user-images.githubusercontent.com/113656415/191204930-d490a3fc-b4f0-45ad-b9d1-3b6b780f4c83.gif)

Should be fixed in latest version.

**Comment by benjypng** [comment]
> This same bug occurs if you sync your graph between multiple machines. The "Apply children as block references" references are valid on the original machine, but invalid on any synced machine.

 Should be fixed in latest version as well.

**Comment by axelav** [comment]
Appears to be working correctly for me now, thanks @hkgnp!
