### ISSUE TITLE
option to disable menu items

### ISSUE THREAD

**Issue by ndc33** [hkgnp/logseq-swapblocks-plugin#9]
Hi, could you allow option to disable adding (the mysterious) "apply children as.." items to the menu. (It adds noise to the interface).

**Comment by benjypng** [comment]
Apply children as allows the user add the child blocks of the original block as references or as text actually.

Apologies I think too much complexity to allow option to show what is in the menu or not. Best to wait for logseq plugin API to provide this native functionality.
